DSA:
  [
    ArrayList,
    BFSGraphList,
    BFSGraphMatrix,
    BinarySearchList,
    BTBFS,
    BubbleSort,
    DoublyLinkedList,
    LinearSearchList,
    MergeSort,
    MinHeap,
    Queue,
    QuickSort,
    RingBuffer,
    SinglyLinkedList,
    Stack,
  ]
